"""
Generate kind-portability shims for Rust physics schemes.

A capgen-emitted Rust cap calls `use ccpp_rust_kinds, only: c_kind_phys`
on the Fortran side and references `KindPhys` (= `f64` or `f32`) on the
Rust side. Both must agree with whatever real kind CAM-SIMA's physics
column was configured for. We emit two files at build time:

    $BLDROOT/generated/ccpp_rust_kinds.F90
    src/physics/rust_physics/ccpp_rs/src/generated/kind.rs

Both files are derived purely from the `kind_phys` string ("REAL64" or
"REAL32"). They are not checked into git -- the .gitignore in
`ccpp_rs/src/generated/` covers `kind.rs`, and `$BLDROOT/generated/` is
under the build tree.

Per RUST_DESIGN.md §7.2 + §11.2.
"""

import os


_F90_TEMPLATE = """\
! Auto-generated by cime_config/gen_rust_kinds.py. Do not edit.
! Mirrors the Rust-side kind in ccpp_rs/src/generated/kind.rs so that
! capgen-emitted bind(C) glue can `use ccpp_rust_kinds, only: c_kind_phys`.
module ccpp_rust_kinds
   use iso_c_binding, only: {c_kind_constant}
   implicit none
   public

   integer, parameter :: c_kind_phys = {c_kind_constant}
end module ccpp_rust_kinds
"""

_RS_TEMPLATE = """\
// Auto-generated by cime_config/gen_rust_kinds.py. Do not edit.
// Mirrors the Fortran-side `c_kind_phys` in ccpp_rust_kinds.F90.

pub type KindPhys = {rust_type};
"""


def _kind_phys_to_c_constant(kind_phys: str) -> str:
    """Map a CAM-SIMA kind_phys string to the iso_c_binding constant."""
    norm = kind_phys.upper()
    if norm == "REAL64":
        return "c_double"
    if norm == "REAL32":
        return "c_float"
    raise ValueError(
        f"Unsupported kind_phys '{kind_phys}'. Expected 'REAL64' or 'REAL32'."
    )


def _kind_phys_to_rust_type(kind_phys: str) -> str:
    norm = kind_phys.upper()
    if norm == "REAL64":
        return "f64"
    if norm == "REAL32":
        return "f32"
    raise ValueError(
        f"Unsupported kind_phys '{kind_phys}'. Expected 'REAL64' or 'REAL32'."
    )


def _write_if_changed(path: str, content: str) -> bool:
    """Write `content` to `path` only if it differs from existing contents.

    Returns True if the file was written or created. Idempotent so that
    re-running buildlib without a kind change does not invalidate downstream
    Make-based dependency timestamps.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == content:
                return False
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return True


def gen_rust_kinds(kind_phys: str, bld_generated_dir: str,
                   ccpp_rs_generated_dir: str) -> None:
    """Emit ccpp_rust_kinds.F90 and ccpp_rs/src/generated/kind.rs.

    Args:
        kind_phys: "REAL64" or "REAL32".
        bld_generated_dir: directory where ccpp_rust_kinds.F90 is written.
            Typically `$BLDROOT/generated/`.
        ccpp_rs_generated_dir: directory where kind.rs is written.
            Typically `<CAM-SIMA>/src/physics/rust_physics/ccpp_rs/src/generated/`.
    """
    f90_path = os.path.join(bld_generated_dir, "ccpp_rust_kinds.F90")
    rs_path = os.path.join(ccpp_rs_generated_dir, "kind.rs")

    f90_content = _F90_TEMPLATE.format(
        c_kind_constant=_kind_phys_to_c_constant(kind_phys)
    )
    rs_content = _RS_TEMPLATE.format(
        rust_type=_kind_phys_to_rust_type(kind_phys)
    )

    _write_if_changed(f90_path, f90_content)
    _write_if_changed(rs_path, rs_content)
