// Build script: ensure src/generated/kind.rs is present and matches
// whatever `kind_phys` the consumer expects.
//
// Authoritative source: cime_config/gen_rust_kinds.py writes both
// kind.rs and ccpp_rust_kinds.F90 during CAM-SIMA's case.build. For
// standalone `cargo test` / developer iteration the file may not
// exist or may be stale from a previous case.build (e.g. REAL32 left
// behind after a REAL32 case run, where the developer now wants
// REAL64). This script reconciles both paths:
//
// - If env `CAM_KIND_PHYS=REAL64|REAL32` is set, rewrite kind.rs to
//   match (overwriting any stale file). buildlib should set this when
//   invoking cargo so the kind choice is single-sourced from the
//   case configuration.
// - Otherwise, if kind.rs already exists, leave it alone (it was
//   written by an earlier gen_rust_kinds.py or build.rs run).
// - Otherwise, fall back to REAL64 so standalone `cargo test`
//   succeeds without a prior case.build.
//
// Cargo reruns this script when either the env var or kind.rs itself
// changes. Per RUST_DESIGN.md §7.2.

use std::env;
use std::fs;
use std::path::PathBuf;

fn render(kind_phys: &str) -> String {
    let rust_type = match kind_phys {
        "REAL32" => "f32",
        _ => "f64",
    };
    format!(
        "// Auto-generated by ccpp_rs/build.rs (CAM_KIND_PHYS={}).\n\
         // Overwritten by cime_config/gen_rust_kinds.py during case.build.\n\
         \n\
         pub type KindPhys = {};\n",
        kind_phys, rust_type
    )
}

fn main() {
    println!("cargo:rerun-if-env-changed=CAM_KIND_PHYS");
    println!("cargo:rerun-if-changed=src/generated/kind.rs");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let kind_rs = manifest.join("src").join("generated").join("kind.rs");
    fs::create_dir_all(kind_rs.parent().unwrap()).unwrap();

    if let Ok(kind) = env::var("CAM_KIND_PHYS") {
        // Authoritative: env wins. Overwrite unconditionally.
        fs::write(&kind_rs, render(&kind)).unwrap();
        return;
    }

    if !kind_rs.exists() {
        // No env, no file: pick a deterministic default.
        fs::write(&kind_rs, render("REAL64")).unwrap();
    }
    // Else: leave existing kind.rs alone (gen_rust_kinds.py wrote it).
}
